# 1. Parallelizing Neural Network Training with TensorFlow
## 1. First steps with TensorFlow

In [4]:
import tensorflow as tf
print('TensorFlow version:', tf.__version__)
import numpy as np

np.set_printoptions(precision=3)

TensorFlow version: 2.0.0


## 2. Creating tensors in TensorFlow

In [5]:
a = np.array([1, 2, 3], dtype=np.int32)
b = [4, 5, 6]

t_a = tf.convert_to_tensor(a)
t_b = tf.convert_to_tensor(b)

print(t_a)
print(t_b)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor([4 5 6], shape=(3,), dtype=int32)


### 1. Checking if an variable is a tensor

In [6]:
tf.is_tensor(a), tf.is_tensor(t_a)

(False, True)

### 2. Chekcing the shape of a tensor

In [ ]:
t_ones = tf.ones((2, 3))

t_ones.shape

### 3. Accessing the values a tensor refers to

In [ ]:
t_ones.numpy()

### 4. Creating a tensor of constant values

In [7]:
const_tensor = tf.constant([1.2, 5, np.pi], dtype=tf.float32)

print(const_tensor)

tf.Tensor([1.2   5.    3.142], shape=(3,), dtype=float32)


## 3. Manipulating the data type and shape of a tensor
### 1. Changing the datatype of a tensor

In [ ]:
t_a_new = tf.cast(t_a, tf.int64)

print(t_a_new.dtype)

### 2. Transposing a tensor

In [ ]:
t = tf.random.uniform(shape=(3, 5))

t_tr = tf.transpose(t)
print(t.shape, ' --> ', t_tr.shape)

### 3. Reshaping a tensor (for example, from a 1D vector to a 2D array)

In [9]:
t = tf.zeros((30,))

t_reshape = tf.reshape(t, shape=(5, 6))

print(t_reshape.shape)

(5, 6)


### 4. Removing the unnecessary dimensions (dimensions that have size 1, which are not needed)

In [8]:
t = tf.zeros((1, 2, 1, 4, 1))

t_sqz = tf.squeeze(t, axis=(2, 4))

print(t.shape, ' --> ', t_sqz.shape)

(1, 2, 1, 4, 1)  -->  (1, 2, 4)


## 4. Applying mathematical operations to tensors
### 1. Instantiating random tensors with uniform or a standard normal distribution

In [11]:
tf.random.set_seed(1)

t1 = tf.random.uniform(shape=(5, 2), 
                       minval=-1.0,
                       maxval=1.0)

t2 = tf.random.normal(shape=(5, 2), 
                      mean=0.0,
                      stddev=1.0)

### 2. Computing the element-wise product of t1 and t2

In [12]:
t3 = tf.multiply(t1, t2).numpy()
print(t3)

[[-0.27  -0.874]
 [-0.017 -0.175]
 [-0.296 -0.139]
 [-0.727  0.135]
 [-0.401  0.004]]


### 3. Computing the mean, sum, or standard deviation along a certain axis (or axes) using tf.math.reduce_*

In [13]:
t4 = tf.math.reduce_mean(t1, axis=0)

print(t4)

tf.Tensor([0.09  0.207], shape=(2,), dtype=float32)


### 4. Computing the matrix-matrix product between t1 and t2

In [14]:
t5 = tf.linalg.matmul(t1, t2, transpose_b=True)

print(t5.numpy())

[[-1.144  1.115 -0.87  -0.321  0.856]
 [ 0.248 -0.191  0.25  -0.064 -0.331]
 [-0.478  0.407 -0.436  0.022  0.527]
 [ 0.525 -0.234  0.741 -0.593 -1.194]
 [-0.099  0.26   0.125 -0.462 -0.396]]


In [15]:
t6 = tf.linalg.matmul(t1, t2, transpose_a=True)

print(t6.numpy())

[[-1.711  0.302]
 [ 0.371 -1.049]]


### 5. Computing the Lp norm of a tensor (in this case L2 norm)

In [17]:
norm_t1 = tf.norm(t1, ord=2, axis=1).numpy()

print(norm_t1)

[1.046 0.293 0.504 0.96  0.383]


## 5. Split, stack, and concatenate tensors